### ISSUE TITLE
Catkin issue Failed Patch: 0001-Workaround-error-issue-ros-overlay-711.patch

### ISSUE THREAD

**Issue by mcaniot** [awesomebytes/ros_overlay_on_gentoo_prefix#4]
In order to fix "Failed to emerge ros-kinetic/catkin-0.7.20-r1" because of the patch 0001-Workaround-error-issue-ros-overlay-711.patch, you need to remove it from ros-overlay and ebuild the manifest. Add these commands can be a quick workaround for now : 
`RUN rm /tmp/gentoo/var/repo/ros-overlay/ros-kinetic/catkin/files/0001-Workaround-error-issue-ros-overlay-711.patch`
`RUN $PREFIXED ebuild /tmp/gentoo/var/repo/ros-overlay/ros-kinetic/catkin/*.ebuild manifest
`

**Comment by awesomebytes** [comment]
We should probably file a PR on ros-overlay to fix this. Re-making the patch to patch correctly if that's the issue (the double -l-lpthread protection needs to be done if not fixed in catkin itself).

I'm away until next week. I'll take a look then.

**Comment by awesomebytes** [comment]
I just checked, and it seems that patch is unnecessary now. In this commit upstream in catkin they fixed it:
https://github.com/ros/catkin/commit/c3c645b9821f78e2ef5a15e57874e44c7b4d53c7

I made a PR with the removal of the patches: https://github.com/ros/ros-overlay/pull/934

**Comment by awesomebytes** [comment]
I've commited a workaround to keep the nightly builds going until the PR is merged. Once it's merged the workaround will fail and I'll remove it.

Thanks for reporting @mcaniot !
